### ISSUE TITLE
Apfelstrudel falsch

### ISSUE THREAD

**Issue by flokru** [pep-dortmund/soak-cooking#1]
Dem Apfelstrudel fehlen Rosinen. Und Semmelbrösel.

Siehe: 
- https://www.bmlfuw.gv.at/land/lebensmittel/trad-lebensmittel/speisen/apfelstrudel.html
- http://www.austria.info/ch/aktivitaten/essen-und-trinken/osterreichische-rezepte/osterreichische-desserts/apfelstrudel

**Comment by maxnoe** [comment]
Semmelbrösel wurden am Freitag getestet und für gut befunden.

Rosinen sind immer gut.

**Comment by flokru** [comment]
Haha. Sehr gut. 👍🏼
